# serverless deploy --aws-profile tanmay
service: placement-socket

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  profile: tanmay
  environment:
    DYNAMODB_TABLE: 'PlacementSocketStudents'
    DYNAMODB_TABLE_COMPANY: 'PlacementSocketCompanies'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      # Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
      Resource: "*"

    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  registerStudent:
    handler: src/registerStudent.register
    events:
      - http:
          path: registerStudent
          method: post
          cors: true

  addCompany:
      handler: src/addCompany.add
      events:
        - http:
            path: addCompany
            method: post
            cors: true          

resources:
  Resources:

    PlacementSocketDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
    PlacementSocketCompaniesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE_COMPANY}
